version: '3.8'

services:
  autogen-m1:
    image: autogen-m1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web:/app/web
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
