version: '3.8'

services:
  autogenm1:
    image: autogen-m1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/app/input:ro
      - ./output:/app/output
      - ./main.py:/app/main.py:ro
    ports:
      - "5005:5005"
#    network_mode: host
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
